# Generated by Django 4.0 on 2021-12-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
