# Generated by Django 4.0 on 2021-12-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_alter_comments_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='blog',
            new_name='idea',
        ),
    ]
