# Generated by Django 4.0 on 2021-12-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_rename_blog_comments_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='tag_name',
            field=models.CharField(default='Tag', max_length=20),
        ),
    ]
