# Generated by Django 4.0 on 2021-12-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_idea_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='tag_name',
            field=models.CharField(default='general', max_length=20),
        ),
    ]
